### ISSUE TITLE
Does the repo work with opam 2.x?

### ISSUE THREAD

**Issue by Kakadu** [ocamllabs/multicore-opam#4]
I can't see interesting compiler after an upgrade. Maybe it is an OPAM issue, I just want to check do you heard something?

**Comment by kayceesrk** [comment]
I haven't tested the repo with OPAM 2.x. Is the compiler not showing up even after you add the remote?

**Comment by Kakadu** [comment]
Yeah, no compiler. I think it could be opam repository upgrade issue.

**Comment by Kakadu** [comment]
The right command was 
````
    opam switch create 4.02.2+multicore --repositories \
       multicore=git+https://github.com/ocamllabs/multicore-opam,default


````
