### ISSUE TITLE
ocaml-migrate-parsetree

### ISSUE THREAD

**Issue by jhwoodyatt** [ocamllabs/multicore-opam#7]
I've got a local branch of the **ocaml-migrate-parsetree** project augmented for comprehension of the new algebraic effects syntax in the multicore variant compiler? How should I package it for availability in this remote repository?

- As a patch file against the current release?

- As a git branch on a clone that I could push to my github account?

- Somethine else?

Please advise.

**Comment by kayceesrk** [comment]
Thanks @jhwoodyatt  :-) 

I am not sure I understand the difference between suggestions 1 and 2. Wouldn't you need both? For example, here is ssl.0.5.3 that @dhil packaged up which points to an archive in his clone of the original repo.

**Comment by jhwoodyatt** [comment]
To explain the alternatives:

1. I could post a pull request that would comprise a new patch file and a modification to the **opam** files that applies it to the existing source distribution for the released ocaml-migrate-parsetree version.

1. I could post a pull request that would modify the **opam** files to use a _git+https_ scheme URL that would download the latest working sources for ocaml-migrate-parsetree project modified as necessary for the current multicore variant.

I'm not sure which of these two options is preferred by the multicore team.

**Comment by jhwoodyatt** [comment]
Wait. I'm using OPAM 2.0, so doing it the way @dhil did it for _ssl.0.5.3_ may be the right way to do it for OPAM 1.2.

**Comment by kayceesrk** [comment]
@yallop thoughts on this?

**Comment by yallop** [comment]
My preferred approach is the second: push the changes to ocaml-migrate-parsetree to a branch somewhere, and add an opam package here that downloads the archive from that branch.  It looks like that's @dhil's approach, too.

A couple of notes:
 * there's no need to use git+https -- GitHub will build an archive file automatically if you give it a suitable URL, so plain https is fine
 * tags are more stable than branches if there's a stable compiler release available (e.g. the 4.06.1 multicore release) to use in the package constraints.  In other words, once there's a branch of ocaml-migrate-parsetree working with that compiler, it's a good idea to tag the branch and point the opam files here at that tag

**Comment by jhwoodyatt** [comment]
Okay. When I have some free time again (soon), I'll post such a pull request.

**Comment by jhwoodyatt** [comment]
See #8 which also includes patches for _ppx_tools_.

**Comment by kayceesrk** [comment]
Merged #8. Thanks for the PR!
